language: java
sudo: false # faster builds

jdk:
  - openjdk11
  - oraclejdk11
  - openjdk8
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

install: true

script:
  - travis_wait 30 ./gradlew clean build -x test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - if [ -f dubbo.log ]; then echo "------TAIL of dubbo.log------"; tail -n 1000 dubbo.log; echo "------END of dubbo.log------"; fi
